#
# Example configuration file for illumos.
#

#
# General configuration variables.
#
[options]
build_threads = 4
scan_threads = 4
verbose = true

#
# Variables that configure pkgsrc, where it is, what packages to build, etc.
#
[pkgsrc]
basedir = "/usr/pkgsrc"
make = "/opt/pkg/bin/bmake"
pkgpaths = [
	"mail/mutt",
	"sysutils/coreutils",
]

[scripts]
pkg-scan = "scripts/pkg-scan"
pkg-build = "scripts/pkg-build"
pkg-up-to-date = "scripts/pkg-up-to-date"

[build]
bulklog = "/data/bulklog"
packages = "/data/packages"
keep_wrkdir = false
keep_prefix = false
skip_age_check = false
use_destdir = "yes"
pkg_info = "/opt/pkg/sbin/pkg_info"
unprivileged_user = "pbulk"
use_unprivileged_checksum = true
tar = "/usr/bin/gtar"
prefix = "/opt/pkg"

#
# The sandboxes section defines where sandboxes should be created, and how file
# systems and ancilliary data should be created.
#
# The number of sandboxes that will be created is build_threads if set,
# otherwise 1.
#
# During creation the mounts list is processed in order, and when destroying
# sandboxes it is processed in reverse order.
#
[sandboxes]
basedir = "/chroot"
mounts = [
	{ fs = "lofs", dest = "/devices" },
	{ fs = "lofs", dest = "/dev" },
	{ fs = "fd",   dest = "/dev/fd" },
	{ fs = "proc", dest = "/proc" },
	{ fs = "tmp",  dest = "/tmp", opts = "-o size=1024k" },
	{ fs = "tmp",  dest = "/var/tmp" },
	{ fs = "lofs", dest = "/lib" },
	{ fs = "lofs", dest = "/sbin" },
	{ fs = "lofs", dest = "/usr" },
	{ fs = "lofs", dest = "/bin", src = "/usr/bin" },
	# Directory where this config and support scripts live.
	{ fs = "lofs", dest = "@INITDIR@" },
]
