#
# Example configuration file for macOS.
#

#
# General configuration variables.
#
[options]
build_threads = 4
scan_threads = 4
verbose = true

#
# Variables that configure pkgsrc, where it is, what packages to build, etc.
#
[pkgsrc]
basedir = "/usr/pkgsrc"
make = "/opt/pkg/bin/bmake"
pkgpaths = [
	"mail/mutt",
	"sysutils/coreutils",
]

#
# Shell scripts used for different stages.  Keys ending "_inline" will use
# the specified inline script, otherwise the value is a filename (relative
# to the directory that the config was loaded from if not absolute) that will
# be read in.
#
[scripts]
pkg-scan = "scripts/pkg-scan"
pkg-build = "scripts/pkg-build"

#
# The sandboxes section defines where sandboxes should be created, and how file
# systems and ancilliary data should be created.
#
# The number of sandboxes that will be created is build_threads if set,
# otherwise 1.
#
# During creation the mounts list is processed in order, and when destroying
# sandboxes it is processed in reverse order.
#
[sandboxes]
basedir = "/Volumes/data/chroot"
mounts = [
	{ fs = "dev",  dest = "/dev" },
	{ fs = "tmp",  dest = "/tmp", opts = "-e -s 384m" },
	{ fs = "tmp",  dest = "/var", opts = "-e -s 512m" },
	# Read-only system mounts.
	{ fs = "bind", dest = "/Library", opts = "-r" },
	{ fs = "bind", dest = "/System",  opts = "-r" },
	{ fs = "bind", dest = "/bin",     opts = "-r" },
	{ fs = "bind", dest = "/etc",     opts = "-r", src = "/private/etc" },
	{ fs = "bind", dest = "/sbin",    opts = "-r" },
	{ fs = "bind", dest = "/usr",     opts = "-r" },
	# Read-write system mounts.
	{ fs = "bind", dest = "/private/var/spool/postfix" },
	# Directory where this config and support scripts live.
	{ fs = "bind", dest = "@INITDIR@" },
]
