#
# Example configuration file for NetBSD.
#

#
# General configuration variables.
#
[options]
build_threads = 4
scan_threads = 4
verbose = true

#
# Variables that configure pkgsrc, where it is, what packages to build, etc.
#
[pkgsrc]
basedir = "/usr/pkgsrc"
make = "/usr/bin/make"
pkgpaths = [
	"mail/mutt",
	"sysutils/coreutils",
]

#
# Shell scripts used for different stages.  Keys ending "_inline" will use
# the specified inline script, otherwise the value is a filename (relative
# to the directory that the config was loaded from if not absolute) that will
# be read in.
#
[scripts]
pkg-scan = "pkg-scan"
pkg-build = "pkg-build"

#
# The sandboxes section defines where sandboxes should be created, and how file
# systems and ancilliary data should be created.
#
# The number of sandboxes that will be created is build_threads if set,
# otherwise 1.
#
# During creation the mounts list is processed in order, and when destroying
# sandboxes it is processed in reverse order.
#
[sandboxes]
basedir = "/data/chroot"
mounts = [
	{ fs = "dev",  dest = "/dev" },
	{ fs = "proc", dest = "/proc" },
	{ fs = "tmp",  dest = "/tmp", opts = "-s 1024k" },
	{ fs = "tmp",  dest = "/var/tmp" },
	# These are taken verbatim from mksandbox, still correct?
	{ fs = "null", dest = "/bin" },
	{ fs = "null", dest = "/sbin" },
	{ fs = "null", dest = "/libexec" },
	{ fs = "null", dest = "/lib" },
	{ fs = "null", dest = "/usr/X11R7" },
	{ fs = "null", dest = "/usr/bin" },
	{ fs = "null", dest = "/usr/games" },
	{ fs = "null", dest = "/usr/include" },
	{ fs = "null", dest = "/usr/lib" },
	{ fs = "null", dest = "/usr/libdata" },
	{ fs = "null", dest = "/usr/libexec" },
	{ fs = "null", dest = "/usr/share" },
	{ fs = "null", dest = "/usr/sbin" },
	{ fs = "null", dest = "/var/mail" },
]
