/*
 * Copyright (c) 2025 Jonathan Perkin <jonathan@perkin.org.uk>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

//! Bob is a pkgsrc package builder that automates building packages in isolated
//! sandbox environments with parallel build support, dependency resolution, and
//! comprehensive reporting.
//!
//! # Overview
//!
//! Bob provides:
//!
//! - Automatic sandbox setup with platform-specific implementations for Linux,
//!   macOS, NetBSD, and illumos
//! - Dependency scanning and DAG-based resolution for correct build ordering
//! - Parallel scans and builds in separate sandboxes
//! - Terminal UI showing real-time build progress
//! - HTML reports of build results
//! - Lua-based configuration for flexibility
//!
//! # Quick Start
//!
//! ```console
//! $ bob init /path/to/config      # Create configuration directory
//! $ cd /path/to/config
//! $ vi config.lua                 # Customise to taste
//! $ bob build                     # Build packages
//! ```
//!
//! # Modules
//!
//! - [`action`] - Sandbox action types for configuring filesystem mounts, copies,
//!   symlinks, and custom commands
//! - [`build`] - Parallel package builds and result types
//! - [`config`] - Configuration file parsing (Lua format)
//! - [`report`] - HTML build report generation
//! - [`sandbox`] - Sandbox creation, execution, and management
//! - [`scan`] - Package dependency scanning and resolution
//!
//! # Configuration
//!
//! Bob uses Lua configuration files. See the [`config`] module for details on
//! configuration options.  The default file generated by `bob init` is
//! designed to work out of the box with minimal changes on supported operating
//! systems, but you are likely to want to customise it further.

pub mod action;
pub mod build;
pub mod config;
pub mod db;
pub mod report;
pub mod sandbox;
pub mod scan;
pub mod stats;

// Internal modules - exposed for binary use but not primary API
mod init;
pub mod logging;
mod status;
mod tui;

use std::sync::Arc;
use std::sync::atomic::AtomicBool;

/// Shared context for a build or scan run.
pub struct RunContext {
    /// Optional stats collector for performance metrics.
    pub stats: Option<Arc<stats::Stats>>,
    /// Flag to signal graceful shutdown.
    pub shutdown: Arc<AtomicBool>,
}

impl RunContext {
    pub fn new(shutdown: Arc<AtomicBool>) -> Self {
        Self { stats: None, shutdown }
    }

    pub fn with_stats(mut self, stats: Arc<stats::Stats>) -> Self {
        self.stats = Some(stats);
        self
    }
}

// Re-export main types for convenience
pub use action::{Action, ActionType, FSType};
pub use build::{Build, BuildOutcome, BuildResult, BuildSummary};
pub use config::{Config, Options, Pkgsrc, Sandboxes};
pub use db::Database;
pub use report::write_html_report;
pub use sandbox::Sandbox;
pub use scan::{
    ResolvedIndex, Scan, ScanFailure, ScanResult, SkipReason, SkippedPackage,
};
pub use stats::Stats;

// Re-export init for CLI use
pub use init::Init;
